spring:
  application:
    name: NHN Academy - Spring Boot JPA
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.116.64.14:13306/nhn_academy_39
    username: nhn_academy_39
    password: '6]fBj1QmPlpH2c'
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
    open-in-view: false

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.transaction.interceptor: trace
